<?php
require_once '../includes/config.php';
require_once '../includes/auth.php';
require_once '../includes/functions.php';

$auth = new Auth();

if(!$auth->isLoggedIn() || !$auth->isAdmin()) {
    redirect('../login.php');
}

if(!isset($_SESSION['export_data'])) {
    redirect('dashboard.php');
}

$data = $_SESSION['export_data']['data'];
$start_date = $_SESSION['export_data']['start_date'];
$end_date = $_SESSION['export_data']['end_date'];

unset($_SESSION['export_data']);
?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KSC Report - PDF</title>
    <style>
        @media print {
            body { margin: 0; padding: 0; }
            .no-print { display: none !important; }
        }
        
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #000;
        }
        
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        
        .header p {
            margin: 5px 0;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        
        th {
            background-color: #f2f2f2;
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        
        td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        
        .summary {
            margin-bottom: 20px;
        }
        
        .summary-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
        }
        
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>KSC - Komplek Sport Center</h1>
        <p>Booking Report</p>
        <p>Period: <?= formatDate($start_date) ?> - <?= formatDate($end_date) ?></p>
        <p>Generated: <?= date('d/m/Y H:i:s') ?></p>
    </div>
    
    <div class="summary">
        <h3>Summary</h3>
        <div class="summary-row">
            <div><strong>Total Bookings:</strong> <?= count($data) ?></div>
            <div><strong>Total Revenue:</strong> 
                <?= formatCurrency(array_sum(array_column((array)$data, 'jumlah_bayar'))) ?>
            </div>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Booking ID</th>
                <th>Customer</th>
                <th>Lapangan</th>
                <th>Tanggal Main</th>
                <th>Jam</th>
                <th>Total Harga</th>
                <th>Jumlah Bayar</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($data as $row): ?>
            <tr>
                <td>#<?= str_pad($row->id_pemesanan, 4, '0', STR_PAD_LEFT) ?></td>
                <td><?= $row->customer_name ?></td>
                <td><?= $row->nama_lapangan ?></td>
                <td><?= formatDate($row->tanggal) ?></td>
                <td><?= substr($row->jam_mulai, 0, 5) ?>-<?= substr($row->jam_selesai, 0, 5) ?></td>
                <td><?= formatCurrency($row->total_harga) ?></td>
                <td><?= formatCurrency($row->jumlah_bayar) ?></td>
                <td><?= $row->status_pemesanan ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    
    <div class="footer">
        <p>Report generated by KSC System</p>
        <p>Jl. Olahraga No. 123, Jakarta | Telp: (021) 123-4567</p>
    </div>
    
    <div class="no-print" style="text-align: center; margin-top: 20px;">
        <button onclick="window.print()" class="btn btn-primary">
            <i class="fas fa-print"></i> Print Report
        </button>
        <button onclick="window.close()" class="btn btn-secondary">
            <i class="fas fa-times"></i> Close
        </button>
    </div>
    
    <script>
        // Auto-print when page loads
        window.onload = function() {
            window.print();
        }
    </script>
</body>
</html>